
version: '3.7'

services:
  # https://hub.docker.com/r/atlassian/confluence-server
  confluence:
    image: atlassian/confluence-server:6.13.4
    container_name: confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - "~/WORKSPACES/confluence-home:/var/atlassian/application-data/confluence"
