
version: '3.7'

services:
  db:
# docker run -d  -p 5432:5432 \
# --name postgres \
# -e POSTGRES_USER=postgres \
# -e POSTGRES_PASSWORD=mysecretpassword \
# -v postgresData:/var/lib/postgresql/data \
# postgres:10
    image: postgres:10
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "~/confluence/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
# docker run -p 5050:80 \
#   --name pgadmin \
#   -e 'PGADMIN_DEFAULT_EMAIL=postgres' \
#   -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
#   -v pgadminData:/pgadmin4 \
#   -v pgAdminApplicationData:/var/lib/pgadmin \
#   -d dpage/pgadmin4
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    links:
      - "db:db"
    # volumes:
    #   - "~/confluence/pgadmin:/pgadmin4"
    #   - "~/confluence/pgadmindata:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@soul.it
      - PGADMIN_DEFAULT_PASSWORD=admin
  # https://hub.docker.com/r/atlassian/confluence-server
  confluence:
    depends_on:
      - db
    image: atlassian/confluence-server:7.6
    container_name: confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    links:
      - "db:db"
    volumes:
      - "~/confluence/home:/var/atlassian/application-data/confluence"
