labels:
  - issue154
  - test
  - markdown
  - commonmark
home:
  uri: ""
  name: "Test Anchor"
  anchor: true
  children:
    - name: "TEST ISSUE 154 - COMMONMARK"
      uri: ../issue154/home.md
      attachments:
        - name: image2.png
          uri: ../attachments/GvpDashboard2.png
          contentType: image/png
          comment: sample image 2
      children:
        - name: "blockquote"
          uri: ../issue154/cheatsheet/blockquote.md
        - name: "code"
          uri: ../issue154/cheatsheet/code.md
        - name: "emphasis"
          uri: ../issue154/cheatsheet/emphasis.md
        - name: "headers"
          uri: ../issue154/cheatsheet/headers.md
        - name: "horizontal rule"
          uri: ../issue154/cheatsheet/horizontalrule.md
        - name: "images"
          uri: ../issue154/cheatsheet/images.md
          attachments:
            - name: image1.png
              uri: ../attachments/GvpDashboard.png
              contentType: image/png
              comment: sample image 1
        - name: "inline html"
          uri: ../issue154/cheatsheet/inlinehtml.md
        - name: "links"
          uri: ../issue154/cheatsheet/links.md
        - name: "lists"
          uri: ../issue154/cheatsheet/lists.md
        - name: "notice block"
          uri: ../issue154/cheatsheet/noticeblock.md
        - name: "tables"
          uri: ../issue154/cheatsheet/tables.md
